CREATE DATABASE IF NOT EXISTS `board_inbti`

CREATE TABLE if NOT EXISTS `board`(
`id` BIGINT(20) NOT NULL AUTO_INCREMENT comment 'PK',
`title` VARCHAR(200) NOT NULL COMMENT '제목',
`content` TEXT NOT NULL COMMENT '내용',
`read_cnt` INT(11) NOT NULL DEFAULT 0 COMMENT '조회수',
`register_id` VARCHAR(100) NOT NULL COMMENT '작성자',
`register_time` DATETIME NULL DEFAULT NULL COMMENT '작성일',
`update_time` DATETIME NULL DEFAULT NULL COMMENT '수정일',
PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb3 COMMENT='게시판';